const DATA=window.LOCKE_DATA,$=s=>document.querySelector(s),money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n),iso=d=>d.toISOString().slice(0,10),parse=s=>new Date(s+"T12:00:00"),sameMonth=(d,m)=>d.getFullYear()===m.getFullYear()&&d.getMonth()===m.getMonth();
let shown=new Date(2026,8,1);const today=parse("2026-09-12"),horizon=new Date(today);horizon.setMonth(horizon.getMonth()+6);
function eventsOn(d){let s=iso(d);return DATA.events.filter(e=>s>=e.start&&s<=e.end)}function hotelFor(d){return DATA.monthlyHotel[iso(d).slice(0,7)]||DATA.market.normalHotel}function targetFor(d){let ev=eventsOn(d),hotel=Math.round(hotelFor(d)*DATA.market.roomsReplaced*.82/25)*25;return Math.max(275,hotel,...ev.map(e=>e.rate))}function heat(rate){return rate<350?"#edf2ea":rate<400?"#dce8d4":rate<450?"#e9dfb9":rate<500?"#e5bf85":"#d99768"}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".nav,.page").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.page).classList.add("active")});
function renderCalendar(){let y=shown.getFullYear(),m=shown.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),days=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];$("#monthTitle").textContent=shown.toLocaleString("en-US",{month:"long",year:"numeric"});let html=days.map(x=>`<div class="weekday">${x}</div>`).join("");for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let ev=eventsOn(d),out=!sameMonth(d,shown);html+=`<div class="day ${out?"out":""}"><span class="daynum">${d.getDate()}</span>${ev.slice(0,2).map(e=>`<span class="event-pill ${e.type}">${e.icon} ${e.name}</span>`).join("")}${!out?`<span class="rate">${money(targetFor(d))}</span>`:""}</div>`}$("#monthGrid").innerHTML=html;let monthEvents=DATA.events.filter(e=>e.start.slice(0,7)===iso(first).slice(0,7)||e.end.slice(0,7)===iso(first).slice(0,7)||e.start<iso(first)&&e.end>=iso(first));$("#eventList").innerHTML=monthEvents.map(e=>`<article class="event-card"><strong>${e.icon} ${e.name}</strong><span>${new Date(e.start+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"})}–${new Date(e.end+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"})} · ${e.status}</span></article>`).join("")||`<article class="event-card"><strong>No major event currently listed</strong><span>Good candidate for flexible or value pricing.</span></article>`}
$("#prevMonth").onclick=()=>{shown.setMonth(shown.getMonth()-1);renderCalendar()};$("#nextMonth").onclick=()=>{shown.setMonth(shown.getMonth()+1);renderCalendar()};
function renderForecast(){let html="",cursor=new Date(today.getFullYear(),today.getMonth(),1);for(let n=0;n<7;n++){let first=new Date(cursor.getFullYear(),cursor.getMonth()+n,1),last=new Date(first.getFullYear(),first.getMonth()+1,0),cells='<div class="label">S</div><div class="label">M</div><div class="label">T</div><div class="label">W</div><div class="label">T</div><div class="label">F</div><div class="label">S</div>';for(let i=0;i<first.getDay();i++)cells+='<div class="mini-day empty"></div>';for(let d=1;d<=last.getDate();d++){let dt=new Date(first.getFullYear(),first.getMonth(),d),rate=targetFor(dt);cells+=`<button class="mini-day" style="background:${heat(rate)}" data-date="${iso(dt)}" data-rate="${rate}">${d}</button>`}html+=`<article class="forecast-month"><h3>${first.toLocaleString("en-US",{month:"long",year:"numeric"})}</h3><div class="mini-grid">${cells}</div></article>`}$("#forecastGrid").innerHTML=html;document.querySelectorAll(".mini-day[data-date]").forEach(b=>b.onclick=()=>{let d=parse(b.dataset.date),ev=eventsOn(d);$("#dayDetail").innerHTML=`<strong>${d.toLocaleDateString("en-US",{weekday:"short",month:"long",day:"numeric"})}: ${money(+b.dataset.rate)} target</strong><span>Nearby hotel est. ${money(hotelFor(d))}/room${ev.length?" · "+ev.map(x=>x.name).join(", "):" · Normal demand"}</span>`})}
function calculate(a,b){let start=parse(a),end=parse(b),n=Math.max(1,Math.round((end-start)/864e5)),dates=[];for(let d=new Date(start);d<end;d.setDate(d.getDate()+1))dates.push(new Date(d));let peak=Math.max(...dates.map(targetFor)),ev=[...new Set(dates.flatMap(eventsOn).map(e=>e.name))],factors=[.75,.85,1,1.1,1.2],names=["Friends & family","Very good deal","Target","Strong demand","Peak ask"];$("#quoteSummary").innerHTML=`<strong>${n} nights</strong> · ${ev.length?ev.join(" + "):"No major listed event"} · peak market target ${money(peak)}/night`;$("#quoteCards").innerHTML=factors.map((f,i)=>{let nightly=Math.round(Math.max(275,peak*f)/25)*25,total=nightly*n+DATA.market.cleaningFee,airbnb=total*(1+DATA.market.airbnbGuestFee);return`<article class="quote-card ${i===2?"target":""}"><small>${i+1} · ${names[i]}</small><b>${money(nightly)}</b><span>per night · ${money(total)} total</span><em>Guest saves about ${money(airbnb-total)}</em></article>`}).join("")}
$("#quoteForm").onsubmit=e=>{e.preventDefault();if($("#departure").value<=$("#arrival").value)return alert("Departure must be after arrival.");calculate($("#arrival").value,$("#departure").value)};
$("#lastUpdated").textContent=DATA.lastUpdated;$("#arrival").value="2026-10-09";$("#departure").value="2026-10-16";renderCalendar();renderForecast();calculate($("#arrival").value,$("#departure").value);
